name: credentials_crypto_service
description: Dart package which allows to encrypt and decrypt data using AES algorithm.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  encrypt: ^5.0.1

dev_dependencies:
  test: ^1.22.0

  very_good_analysis: ^3.0.1