name: password_keeper
description: Password keeper app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  loading_animation_widget:
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  firebase_ui_auth: ^1.0.0-dev.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  curved_navigation_bar: ^1.0.3
  anim_search_bar: ^2.0.2
  google_fonts: ^3.0.1

  # local
  credentials_repository:
    path: packages/credentials_repository
  firestore_credentials_service:
    path: packages/firestore_credentials_service
  credentials_service:
    path: packages/credentials_service
  credentials_crypto_service:
    path: packages/credentials_crypto_service
  firebase_auth_mocks: ^0.9.1
  fake_cloud_firestore: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  bloc_test: ^9.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/