name: authentication_repository
description: Dart package which manages the authentication.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  very_good_analysis: ^3.0.1
